name: Update GFG Stats

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-gfg-stats:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate GFG Stats Card
        run: |
          node scripts/generate-gfg-card.mjs rahulyadavjq1w

      - name: Commit updated GFG stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/gfg-stats.svg

          git diff --cached --quiet || git commit -m "Update GFG stats"

      - name: Push changes
        run: |
          git push
